### ISSUE TITLE
request: adwaita accent color support?

### ISSUE THREAD

**Issue by CodedIsTaken** [egirlcatnip/adwaita-github-theme#3]
i'm asking for you to add adwaita accent color support.

**Comment by egirlcatnip** [comment]
Can you elaborate what elements would be changed to the theme colors?

**Comment by CodedIsTaken** [comment]
The gnome 47 accent colors, it might have potential for vscode.

**Comment by egirlcatnip** [comment]
I'm aware of the accent colors.
What elements of the theme would be changed? 
Also it might not be easily configurable to make the theme switch dynamically, perhaps having a variant for each accent could work.

**Comment by CodedIsTaken** [comment]
the blue accents of vscode.

**Comment by egirlcatnip** [comment]
this is a bit too much work for myself currently. I'm busy with school, so this will not be implemented for a while, if ever.
